#!/bin/bash

#This bash script takes as an input the dump.out file generated by the mclblastline pipeline.
#The script returns the gene frequecies for each family (row) in each genome (column)

#A list of genomes must be provided in a one column file named locustags.txt

#Francesca Bottacini, APC BioIT platform, University College Cork
# <f.bottacini@umail.ucc.ie>


input=${1};

# separate the gene ids from the genome ids
sed -e 's/_/\t/g' ${input} > ${input}.tmp

#Generate an array of genome ids
genids=`cat locustags.txt | tr -s "\n" " "; echo ""`

for genid in ${genids[@]}; do
echo -en "\t$genid";
done
echo "";

while read line; do
fams=$(echo $line|cut -d " " -f 1 );
echo -en "$fams\t";
for genid in ${genids[@]}; do
freq=`echo $line | awk -F "$genid" '{print NF-1}'`;
echo -ne "$freq\t";
done
echo ""; done<${input}.tmp ;

#Cleanup
rm ${input}.tmp;
